ColumnNames:
  CustomerID: int
  ProdTaken: int  
  Age: float
  CityTier: int
  DurationOfPitch: float
  NumberOfPersonVisiting: int
  NumberOfFollowups: float
  PreferredPropertyStar: float
  NumberOfTrips: float
  Passport: int
  PitchSatisfactionScore: int
  OwnCar: int
  NumberOfChildrenVisiting: float
  MonthlyIncome: float
  TypeofContact: category
  Occupation: category
  Gender: category
  ProductPitched: category
  MaritalStatus: category
  Designation: category

Numerical_columns:
  - CustomerID
  - ProdTaken
  - Age
  - CityTier
  - DurationOfPitch
  - NumberOfPersonVisiting
  - NumberOfFollowups
  - PreferredPropertyStar
  - NumberOfTrips
  - Passport
  - PitchSatisfactionScore
  - OwnCar
  - NumberOfChildrenVisiting
  - MonthlyIncome

Categorical_columns:
  - TypeofContact
  - Occupation
  - Gender
  - ProductPitched
  - MaritalStatus
  - Designation


Discrete_columns:
  - CityTier
  - NumberOfPersonVisiting
  - NumberOfFollowups
  - PreferredPropertyStar
  - NumberOfTrips
  - Passport
  - PitchSatisfactionScore
  - OwnCar
  - NumberOfChildrenVisiting

Continuous_columns:
  - Age
  - DurationOfPitch
  - MonthlyIncome

Transformation_columns:
  - DurationOfPitch
  - MonthlyIncome

Drop_columns:
  - CustomerID

target_column: ProdTaken